import fs from "fs";
import { stat } from "fs/promises";
import path from "path";
import { execFile } from "child_process";
import { promisify } from "util";
import { NextResponse } from "next/server";
import { google } from "googleapis";
import { createYoutubeOAuthClient, verifyYoutubeChannelWithClient } from "@/lib/youtube";

const execFileAsync = promisify(execFile);
const MAX_VIDEO_SIZE_BYTES = 512 * 1024 * 1024;
const TMP_ROOT = path.resolve(process.cwd(), "tmp");
const ALLOWED_THUMBNAIL_EXTENSIONS = new Set([".png", ".jpg", ".jpeg", ".svg"]);

function resolveSafeTmpPath(inputPath: string) {
  const resolved = path.resolve(inputPath);
  const relative = path.relative(TMP_ROOT, resolved);

  if (relative.startsWith("..") || path.isAbsolute(relative)) {
    throw new Error("Path must be inside tmp directory.");
  }

  return resolved;
}

function readSessionKey(request: Request) {
  const cookieHeader = request.headers.get("cookie") || "";
  const value = cookieHeader
    .split(";")
    .map((part) => part.trim())
    .find((part) => part.startsWith("yt_session_key="))
    ?.slice("yt_session_key=".length);

  return value ? decodeURIComponent(value) : null;
}

async function ensureYoutubeThumbnailPath(inputPath: string) {
  const ext = path.extname(inputPath).toLowerCase();

  if (!ALLOWED_THUMBNAIL_EXTENSIONS.has(ext)) {
    throw new Error("thumbnailPath must be PNG, JPEG, or SVG.");
  }

  if (ext !== ".svg") {
    return inputPath;
  }

  const convertedPath = inputPath.replace(/\.svg$/i, `-${Date.now()}.png`);
  await execFileAsync("ffmpeg", ["-y", "-i", inputPath, convertedPath]);
  return convertedPath;
}

export async function POST(request: Request) {
  try {
    const sessionKey = readSessionKey(request);
    if (!sessionKey) {
      return NextResponse.json({ ok: false, message: "Missing OAuth session. Connect via /oauth first." }, { status: 401 });
    }

    const payload = (await request.json()) as {
      videoPath?: string;
      thumbnailPath?: string;
      title?: string;
      description?: string;
      tags?: string[];
      privacyStatus?: "private" | "public" | "unlisted";
    };

    if (!payload.videoPath) {
      return NextResponse.json({ ok: false, message: "videoPath is required." }, { status: 400 });
    }

    const safeVideoPath = resolveSafeTmpPath(payload.videoPath);
    const videoStats = await stat(safeVideoPath);
    if (videoStats.size > MAX_VIDEO_SIZE_BYTES) {
      return NextResponse.json({ ok: false, message: "Video file exceeds 512MB." }, { status: 400 });
    }

    const oauth2Client = await createYoutubeOAuthClient(sessionKey);
    await oauth2Client.getAccessToken();
    const channel = await verifyYoutubeChannelWithClient(oauth2Client);
    const youtube = google.youtube({ version: "v3", auth: oauth2Client });

    const uploadResponse = await youtube.videos.insert({
      part: ["snippet", "status"],
      requestBody: {
        snippet: {
          title: payload.title || `Generated video - ${new Date().toISOString()}`,
          description: payload.description || "Generated by YouTube Otomatik Video Asistanı",
          tags: payload.tags || ["ai", "video", "youtube"],
        },
        status: {
          privacyStatus: payload.privacyStatus || "private",
        },
      },
      media: {
        body: fs.createReadStream(safeVideoPath),
      },
    });

    const videoId = uploadResponse.data.id;
    if (!videoId) {
      throw new Error("YouTube upload did not return a video ID.");
    }

    if (payload.thumbnailPath) {
      const safeThumbnailPath = resolveSafeTmpPath(payload.thumbnailPath);
      await stat(safeThumbnailPath);

      const youtubeThumbnailPath = await ensureYoutubeThumbnailPath(safeThumbnailPath);

      await youtube.thumbnails.set({
        videoId,
        media: {
          body: fs.createReadStream(youtubeThumbnailPath),
        },
      });
    }

    return NextResponse.json({
      ok: true,
      channel,
      videoId,
      videoUrl: `https://www.youtube.com/watch?v=${videoId}`,
      privacyStatus: payload.privacyStatus || "private",
    });
  } catch (error) {
    console.error("YouTube upload error", error);
    return NextResponse.json(
      { ok: false, message: error instanceof Error ? error.message : "YouTube upload failed." },
      { status: 500 },
    );
  }
}
